#根据不同环境选用不同的配置
server:
  port: 8088
spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/city_topic?serverTimezone=GMT%2B8&amp&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: mirror6

    # 使用德鲁伊数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
#    # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
#    initialSize: 1
#    minIdle: 1
#    maxIdle: 5
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: true
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: false
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    # 合并多个DruidDataSource的监控数据
#    #spring.datasource.useGlobalDataSourceStat=true

  #thymeleaf模版前缀
  thymeleaf:
    prefix: classpath:/public/
    mode: html5
    encoding: utf-8
    servlet:
      content-type: text/html

  #views
  mvc:
    view:
      prefix: classpath:/public/
      suffix: .html
#    static-path-pattern: /static/**

#mybatis扫描设置
mybatis-plus:
  mapper-locations: classpath*:com/mybatis/plus/demo/mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml

#pagehelper分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

# 打印sql
logging:
  level:
    com.mybatis.plus.demo.mapper: debug







